#!/usr/bin/env ruby

# Usage:
#
#   $ note -e How to Use Vim
#   $ cat ~/Dropbox/Notes/Inbox/how-to-use-vim.md
#   ---
#   title: How to Use Vim
#   date: 2018-01-01 00:00:00.000000000 +09:00
#   ---

require 'optparse'
require 'pathname'
require 'yaml'

OUTPUT_DIR = Pathname.new('~/Dropbox/Notes/Inbox').expand_path
OUTPUT_DIR.mkpath

@edit = false

parser = OptionParser.new
parser.banner = "Usage: #{parser.program_name} [-e] WORDS..."
parser.on('-e', 'Open in editor') { @edit = true }
parser.parse!

now = Time.now

title = ARGV.join(' ').strip
slug = title.gsub(/[^0-9A-Z_a-z]+/, ' ').strip.tr(' ', '-').downcase

if title.empty?
  title = 'Untitled'
end

if slug.empty?
  slug = now.strftime('%Y-%m-%d')
end

front_matter = { 'title' => title, 'date' => now }.to_yaml + "---\n"

output_path = OUTPUT_DIR.join(slug + '.md')

unless output_path.exist?
  output_path.write(front_matter)
end

puts output_path

if @edit
  editor = ENV['EDITOR'] || 'vim'
  system(editor, output_path.to_s)
end
